name: E2E
on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: node:14

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Run e2e
        run: npm run test:e2e
        env:
          MONGO_USER: root
          MONGO_PASSWORD: root
          MONGO_HOST: localhost
          MONGO_DB_NAME: demo
          MONGO_PORT: 27017
          MONGO_CONNECTION: mongodb